In [1]:
import pandas as pd
from data_processor import DataProcessor

# if you wanna see how this works, look at the "Feature Engineering" notebook
dp = DataProcessor()
original_df = pd.read_csv("../data/train.csv")
df = dp.encode_data(original_df)
df

,LotFrontage,LotArea,OverallQual,OverallCond,MasVnrArea,BsmtFinSF1,BsmtFinSF2,BsmtUnfSF,TotalBsmtSF,1stFlrSF,...,BsmtFinType2,HeatingQC,Electrical,KitchenQual,Functional,FireplaceQu,GarageQual,GarageCond,PoolQC,SalePrice
0,65.0,8450,7,5,196.0,706,0,150,856,856,...,5.0,0.0,4.0,2.0,6.0,-1.0,4.0,4.0,-1.0,208500
1,80.0,9600,6,8,0.0,978,0,284,1262,1262,...,5.0,0.0,4.0,3.0,6.0,4.0,4.0,4.0,-1.0,181500
2,68.0,11250,7,5,162.0,486,0,434,920,920,...,5.0,0.0,4.0,2.0,6.0,4.0,4.0,4.0,-1.0,223500
3,60.0,9550,7,5,0.0,216,0,540,756,961,...,5.0,2.0,4.0,2.0,6.0,2.0,4.0,4.0,-1.0,140000
4,84.0,14260,8,5,350.0,655,0,490,1145,1145,...,5.0,0.0,4.0,2.0,6.0,4.0,4.0,4.0,-1.0,250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,62.0,7917,6,5,0.0,0,0,953,953,953,...,5.0,0.0,4.0,3.0,6.0,4.0,4.0,4.0,-1.0,175000
1456,85.0,13175,6,6,119.0,790,163,589,1542,2073,...,4.0,4.0,4.0,3.0,2.0,4.0,4.0,4.0,-1.0,210000
1457,66.0,9042,7,9,0.0,275,0,877,1152,1188,...,5.0,0.0,4.0,2.0,6.0,2.0,4.0,4.0,-1.0,266500
1458,68.0,9717,5,6,0.0,49,1029,0,1078,1078,...,4.0,2.0,0.0,2.0,6.0,-1.0,4.0,4.0,-1.0,142125
1459,75.0,9937,5,6,0.0,830,290,136,1256,1256,...,3.0,2.0,4.0,3.0,6.0,-1.0,4.0,4.0,-1.0,147500

In [2]:
num_df = dp.numerical_data(original_df)
num_df

,LotFrontage,LotArea,OverallQual,OverallCond,MasVnrArea,BsmtFinSF1,BsmtFinSF2,BsmtUnfSF,TotalBsmtSF,1stFlrSF,...,GarageCars,GarageArea,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,SalePrice
0,65.0,8450,7,5,196.0,706,0,150,856,856,...,2,548,0,61,0,0,0,0,0,208500
1,80.0,9600,6,8,0.0,978,0,284,1262,1262,...,2,460,298,0,0,0,0,0,0,181500
2,68.0,11250,7,5,162.0,486,0,434,920,920,...,2,608,0,42,0,0,0,0,0,223500
3,60.0,9550,7,5,0.0,216,0,540,756,961,...,3,642,0,35,272,0,0,0,0,140000
4,84.0,14260,8,5,350.0,655,0,490,1145,1145,...,3,836,192,84,0,0,0,0,0,250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,62.0,7917,6,5,0.0,0,0,953,953,953,...,2,460,0,40,0,0,0,0,0,175000
1456,85.0,13175,6,6,119.0,790,163,589,1542,2073,...,2,500,349,0,0,0,0,0,0,210000
1457,66.0,9042,7,9,0.0,275,0,877,1152,1188,...,1,252,0,60,0,0,0,0,2500,266500
1458,68.0,9717,5,6,0.0,49,1029,0,1078,1078,...,1,240,366,0,112,0,0,0,0,142125
1459,75.0,9937,5,6,0.0,830,290,136,1256,1256,...,1,276,736,68,0,0,0,0,0,147500

In [3]:
cat_df = dp.categorical_data(original_df)
cat_df

,MSZoning,Street,Alley,LotShape,LandContour,Utilities,LotConfig,Neighborhood,Condition1,Condition2,...,SaleType,SaleCondition,MSSubClass,YearBuilt,YearRemodAdd,BsmtFullBath,BsmtHalfBath,GarageYrBlt,MoSold,YrSold
0,RL,Pave,NaN,Reg,Lvl,AllPub,Inside,CollgCr,Norm,Norm,...,WD,Normal,60,2003,2003,1,0,2003.0,2,2008
1,RL,Pave,NaN,Reg,Lvl,AllPub,FR2,Veenker,Feedr,Norm,...,WD,Normal,20,1976,1976,0,1,1976.0,5,2007
2,RL,Pave,NaN,IR1,Lvl,AllPub,Inside,CollgCr,Norm,Norm,...,WD,Normal,60,2001,2002,1,0,2001.0,9,2008
3,RL,Pave,NaN,IR1,Lvl,AllPub,Corner,Crawfor,Norm,Norm,...,WD,Abnorml,70,1915,1970,1,0,1998.0,2,2006
4,RL,Pave,NaN,IR1,Lvl,AllPub,FR2,NoRidge,Norm,Norm,...,WD,Normal,60,2000,2000,1,0,2000.0,12,2008
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,RL,Pave,NaN,Reg,Lvl,AllPub,Inside,Gilbert,Norm,Norm,...,WD,Normal,60,1999,2000,0,0,1999.0,8,2007
1456,RL,Pave,NaN,Reg,Lvl,AllPub,Inside,NWAmes,Norm,Norm,...,WD,Normal,20,1978,1988,1,0,1978.0,2,2010
1457,RL,Pave,NaN,Reg,Lvl,AllPub,Inside,Crawfor,Norm,Norm,...,WD,Normal,70,1941,2006,0,0,1941.0,5,2010
1458,RL,Pave,NaN,Reg,Lvl,AllPub,Inside,NAmes,Norm,Norm,...,WD,Normal,20,1950,1996,1,0,1950.0,4,2010
1459,RL,Pave,NaN,Reg,Lvl,AllPub,Inside,Edwards,Norm,Norm,...,WD,Normal,20,1965,1965,1,0,1965.0,6,2008

In [4]:
ord_df = dp.ordinal_data(original_df)
ord_df

,LandSlope,BsmtQual,BsmtCond,BsmtFinType1,BsmtFinType2,HeatingQC,Electrical,KitchenQual,Functional,FireplaceQu,GarageQual,GarageCond,PoolQC
0,Gtl,Gd,TA,GLQ,Unf,Ex,SBrkr,Gd,Typ,NaN,TA,TA,NaN
1,Gtl,Gd,TA,ALQ,Unf,Ex,SBrkr,TA,Typ,TA,TA,TA,NaN
2,Gtl,Gd,TA,GLQ,Unf,Ex,SBrkr,Gd,Typ,TA,TA,TA,NaN
3,Gtl,TA,Gd,ALQ,Unf,Gd,SBrkr,Gd,Typ,Gd,TA,TA,NaN
4,Gtl,Gd,TA,GLQ,Unf,Ex,SBrkr,Gd,Typ,TA,TA,TA,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,Gtl,Gd,TA,Unf,Unf,Ex,SBrkr,TA,Typ,TA,TA,TA,NaN
1456,Gtl,Gd,TA,ALQ,Rec,TA,SBrkr,TA,Min1,TA,TA,TA,NaN
1457,Gtl,TA,Gd,GLQ,Unf,Ex,SBrkr,Gd,Typ,Gd,TA,TA,NaN
1458,Gtl,TA,TA,GLQ,Rec,Gd,FuseA,Gd,Typ,NaN,TA,TA,NaN
1459,Gtl,TA,TA,BLQ,LwQ,Gd,SBrkr,TA,Typ,NaN,TA,TA,NaN